package com.example.hu.mediaplayerapk.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hu.mediaplayerapk.bean.WashingReportItem;

import com.example.hu.mediaplayerapk.dao.WashingReportItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig washingReportItemDaoConfig;

    private final WashingReportItemDao washingReportItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        washingReportItemDaoConfig = daoConfigMap.get(WashingReportItemDao.class).clone();
        washingReportItemDaoConfig.initIdentityScope(type);

        washingReportItemDao = new WashingReportItemDao(washingReportItemDaoConfig, this);

        registerDao(WashingReportItem.class, washingReportItemDao);
    }
    
    public void clear() {
        washingReportItemDaoConfig.clearIdentityScope();
    }

    public WashingReportItemDao getWashingReportItemDao() {
        return washingReportItemDao;
    }

}
